version: "3.8"

services:
  backend:
    build: ./backend # Build backend using Dockerfile in backend directory
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend # Build frontend using Dockerfile in frontend directory
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    mem_limit: 2g
    mem_reservation: 1g
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data:
