version: "3.8"

services:
  backend:
    mem_limit: 2g
    mem_reservation: 1g
    build: .       # Build backend using Dockerfile in backend directory
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=${PORT}

  db:
    mem_limit: 2g
    mem_reservation: 1g
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: