version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=bobbyshmurda66
      - DB_NAME=projecttracker

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bobbyshmurda66
      POSTGRES_DB: projecttracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
